// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from MathUtils.djinni


export interface MathUtils {
    addFff64(a: number, b: number): number;
}
export interface MathUtils_statics {
    createMathUtils(): MathUtils;
}

export interface Module_statics {
    MathUtils: MathUtils_statics;
}
